### ISSUE TITLE
Create an API to receive the new organisation data

### ISSUE THREAD

**Issue by Amwam** [Code-Your-Future/final-project-1#29]

**Comment by sentayhuJo** [comment]
## APIs for distinct list (borough and area) and Insert organisation data to Server.
### Using APIs

- `'/api/organisation/borough'` : It return the distinct list of borough eg 
`fetch('/api/organisation/borough')
.then( responce => responce.json() ).
.then( borough => borough)
` and it will give you.
```json
{
  "data": [
    "Deptford",
    "Haringey",
    "Hounslow",
    "All",
    "Enfield",
    "Newham",
......
]
}
```
**Note:** This is used for lookup when the user select **borough** on the form.

-  `'/api/organisation/area'` : It return the distinct list of Area eg 
`fetch('/api/organisation/Area')
.then( responce => responce.json() ).
.then( area => area)
` and it will give you.
```json
{
  "data": [
    "South",
    "North",
    "West",
    "All",
    "East",
    "Central",
    "London"
....
]
}
```
**Note:** This is used for lookup when the user select **Area** on the form.
-  `'/api/organisation/post'` : It will return boolean for success , throw error otherwise. It accept form data as JSON format then make request.
e.g let data is the variable which has the following json data,
```json
{
        "Area": "Ethiopia",
        "Organisation": "999 Club",
        "Clients": [
            "Homeless/Hostel/Risk of eviction"
        ],
        "Category": "Ethiopia",
        "Email": "office@999club.org",
        "Website": "http://999club.org/our-services/advice-and-support/",
        "Tel": [
            "020 8694 5797"
        ],
        "Process": [
            "Drop-in 10.30am Mon- Fri"
        ],
        "Postcode": "SE8 4PA",
        "Services": "Benefits Advice",
        "Borough": "Deptford",
        "Day": [
            "Mon - Fri"
        ]
    }
```
then, make request like  
` fetch( '/api/organisation/post' + jsonData )
.then( responce => responce)
`
then, the result will be ,
```json {
  "Success": "Saved Succesfully"
}
```
